name: Trigger auto deployment for container-app-zvyu2uyyruwva

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-zvyu2uyyruwva-AutoDeployTrigger-82a9fbb9-cd82-4c51-a357-03f502bce78f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryzvyu2uyyruwva.azurecr.io
          username: ${{ secrets.CONTAINERAPPZVYU2UYYRUWVA_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPZVYU2UYYRUWVA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryzvyu2uyyruwva.azurecr.io/container-app-zvyu2uyyruwva:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPZVYU2UYYRUWVA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-zvyu2uyyruwva -g yelpcamp8ffc --server containerregistryzvyu2uyyruwva.azurecr.io --username  ${{ secrets.CONTAINERAPPZVYU2UYYRUWVA_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPZVYU2UYYRUWVA_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-zvyu2uyyruwva -g yelpcamp8ffc --image containerregistryzvyu2uyyruwva.azurecr.io/container-app-zvyu2uyyruwva:${{ github.sha }}
