name: Trigger auto deployment for container-app-zxmk7qzhlqkps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-zxmk7qzhlqkps-AutoDeployTrigger-6b37a18e-4f89-4962-9b31-91e4d50d210e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryzxmk7qzhlqkps.azurecr.io
          username: ${{ secrets.CONTAINERAPPZXMK7QZHLQKPS_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPZXMK7QZHLQKPS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryzxmk7qzhlqkps.azurecr.io/container-app-zxmk7qzhlqkps:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPZXMK7QZHLQKPS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-zxmk7qzhlqkps -g yelpcampb900 --server containerregistryzxmk7qzhlqkps.azurecr.io --username  ${{ secrets.CONTAINERAPPZXMK7QZHLQKPS_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPZXMK7QZHLQKPS_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-zxmk7qzhlqkps -g yelpcampb900 --image containerregistryzxmk7qzhlqkps.azurecr.io/container-app-zxmk7qzhlqkps:${{ github.sha }}
