name: Trigger auto deployment for container-app-p4uc2qwnhbydq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-p4uc2qwnhbydq-AutoDeployTrigger-1638a2a1-1a99-4216-90a9-33dc94631144.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryp4uc2qwnhbydq.azurecr.io
          username: ${{ secrets.CONTAINERAPPP4UC2QWNHBYDQ_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPP4UC2QWNHBYDQ_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryp4uc2qwnhbydq.azurecr.io/container-app-p4uc2qwnhbydq:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPP4UC2QWNHBYDQ_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-p4uc2qwnhbydq -g yelpcampa99b --server containerregistryp4uc2qwnhbydq.azurecr.io --username  ${{ secrets.CONTAINERAPPP4UC2QWNHBYDQ_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPP4UC2QWNHBYDQ_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-p4uc2qwnhbydq -g yelpcampa99b --image containerregistryp4uc2qwnhbydq.azurecr.io/container-app-p4uc2qwnhbydq:${{ github.sha }}
