name: Trigger auto deployment for container-app-3bbyyn7x3qsc6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-3bbyyn7x3qsc6-AutoDeployTrigger-f6e36b67-9445-4bf7-ac98-44c8724a41ff.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: testcontaienrappcreate.azurecr.io
          username: ${{ secrets.CONTAINERAPP3BBYYN7X3QSC6_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP3BBYYN7X3QSC6_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: testcontaienrappcreate.azurecr.io/container-app-3bbyyn7x3qsc6:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPP3BBYYN7X3QSC6_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-3bbyyn7x3qsc6 -g yelpcamp9adcht --server testcontaienrappcreate.azurecr.io --username  ${{ secrets.CONTAINERAPP3BBYYN7X3QSC6_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP3BBYYN7X3QSC6_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-3bbyyn7x3qsc6 -g yelpcamp9adcht --image testcontaienrappcreate.azurecr.io/container-app-3bbyyn7x3qsc6:${{ github.sha }}
