name: Trigger auto deployment for container-app-s5miceai3mycw

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-s5miceai3mycw-AutoDeployTrigger-5ae66394-7aa0-4542-a71e-076dc3530b1e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrys5miceai3mycw.azurecr.io
          username: ${{ secrets.CONTAINERAPPS5MICEAI3MYCW_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPS5MICEAI3MYCW_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrys5miceai3mycw.azurecr.io/container-app-s5miceai3mycw:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPS5MICEAI3MYCW_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-s5miceai3mycw -g yelpcampa0fb --server containerregistrys5miceai3mycw.azurecr.io --username  ${{ secrets.CONTAINERAPPS5MICEAI3MYCW_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPS5MICEAI3MYCW_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-s5miceai3mycw -g yelpcampa0fb --image containerregistrys5miceai3mycw.azurecr.io/container-app-s5miceai3mycw:${{ github.sha }}
