name: Trigger auto deployment for container-app-6p2jwxn3og3ks

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-6p2jwxn3og3ks-AutoDeployTrigger-e8dde435-a12d-4421-8b0e-1ce13fec7dca.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistry6p2jwxn3og3ks.azurecr.io
          username: ${{ secrets.CONTAINERAPP6P2JWXN3OG3KS_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP6P2JWXN3OG3KS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistry6p2jwxn3og3ks.azurecr.io/container-app-6p2jwxn3og3ks:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPP6P2JWXN3OG3KS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-6p2jwxn3og3ks -g yelpcamp9e83 --server containerregistry6p2jwxn3og3ks.azurecr.io --username  ${{ secrets.CONTAINERAPP6P2JWXN3OG3KS_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP6P2JWXN3OG3KS_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-6p2jwxn3og3ks -g yelpcamp9e83 --image containerregistry6p2jwxn3og3ks.azurecr.io/container-app-6p2jwxn3og3ks:${{ github.sha }}
