name: Trigger auto deployment for container-app-2glp7cmlbzshk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-2glp7cmlbzshk-AutoDeployTrigger-95858146-46d8-4951-bd14-a76d4b5a3649.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistry2glp7cmlbzshk.azurecr.io
          username: ${{ secrets.CONTAINERAPP2GLP7CMLBZSHK_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP2GLP7CMLBZSHK_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistry2glp7cmlbzshk.azurecr.io/container-app-2glp7cmlbzshk:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPP2GLP7CMLBZSHK_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-2glp7cmlbzshk -g yelpcampbc66 --server containerregistry2glp7cmlbzshk.azurecr.io --username  ${{ secrets.CONTAINERAPP2GLP7CMLBZSHK_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP2GLP7CMLBZSHK_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-2glp7cmlbzshk -g yelpcampbc66 --image containerregistry2glp7cmlbzshk.azurecr.io/container-app-2glp7cmlbzshk:${{ github.sha }}
