name: Trigger auto deployment for eawfredfs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/eawfredfs-AutoDeployTrigger-a611529a-4bdd-4f86-aec1-80dc66501062.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrydgphzragcuz3s.azurecr.io
          username: ${{ secrets.EAWFREDFS_REGISTRY_USERNAME }}
          password: ${{ secrets.EAWFREDFS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrydgphzragcuz3s.azurecr.io/eawfredfs:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.EAWFREDFS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n eawfredfs -g DRDrill --server containerregistrydgphzragcuz3s.azurecr.io --username  ${{ secrets.EAWFREDFS_REGISTRY_USERNAME }} --password ${{ secrets.EAWFREDFS_REGISTRY_PASSWORD }}
            az containerapp update -n eawfredfs -g DRDrill --image containerregistrydgphzragcuz3s.azurecr.io/eawfredfs:${{ github.sha }}
