name: Trigger auto deployment for premiun-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/premiun-container-app-AutoDeployTrigger-4ea2a0b8-8253-48a5-9c7a-65c3a401df68.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrye4nklroqbtw5w.azurecr.io
          username: ${{ secrets.PREMIUNCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.PREMIUNCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrye4nklroqbtw5w.azurecr.io/premiun-container-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PREMIUNCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n premiun-container-app -g qltest --server containerregistrye4nklroqbtw5w.azurecr.io --username  ${{ secrets.PREMIUNCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.PREMIUNCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n premiun-container-app -g qltest --image containerregistrye4nklroqbtw5w.azurecr.io/premiun-container-app:${{ github.sha }}
