name: Trigger auto deployment for testminmaxreplicas

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/testminmaxreplicas-AutoDeployTrigger-d8ee422f-6342-42a0-b92f-c6518a697de3.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrymiaaxgbjytjtw.azurecr.io
          username: ${{ secrets.TESTMINMAXREPLICAS_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTMINMAXREPLICAS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrymiaaxgbjytjtw.azurecr.io/testminmaxreplicas:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTMINMAXREPLICAS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n testminmaxreplicas -g qltest --server containerregistrymiaaxgbjytjtw.azurecr.io --username  ${{ secrets.TESTMINMAXREPLICAS_REGISTRY_USERNAME }} --password ${{ secrets.TESTMINMAXREPLICAS_REGISTRY_PASSWORD }}
            az containerapp update -n testminmaxreplicas -g qltest --image containerregistrymiaaxgbjytjtw.azurecr.io/testminmaxreplicas:${{ github.sha }}
