name: Trigger auto deployment for testregistry

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/testregistry-AutoDeployTrigger-b18a79e4-448d-49a0-9f5d-d7100bbf923d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: testcontaienrappcreate.azurecr.io
          username: ${{ secrets.TESTREGISTRY_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTREGISTRY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: testcontaienrappcreate.azurecr.io/testregistry:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTREGISTRY_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n testregistry -g qltest --server testcontaienrappcreate.azurecr.io --username  ${{ secrets.TESTREGISTRY_REGISTRY_USERNAME }} --password ${{ secrets.TESTREGISTRY_REGISTRY_PASSWORD }}
            az containerapp update -n testregistry -g qltest --image testcontaienrappcreate.azurecr.io/testregistry:${{ github.sha }}
